name = better_last_login
description = Improves the default /last-login command with cleaner formatting and relative time.
author = CrazyladMT
title = Better Last Login
optional_depends = canonical_name
